// Invitation provider abstraction.
//
// Per `project_external_integrations_architecture.md`, every
// external-channel surface goes through a Qift-owned interface.
// The invitation provider seam supports a future where SMS, email,
// or platform-approved social DMs can actually send invitations
// directly. TODAY there is exactly ONE implementation:
//
//   ManualShareProvider — generates the public URL + a calm,
//                         privacy-aware suggested message that the
//                         SENDER copies and shares MANUALLY through
//                         their own preferred channel.
//
// Future implementations (NOT IN SCOPE for MVP; documented for the
// architectural seam only):
//
//   SmsInviteProvider     — sends an SMS via Unifonic / Taqniyat /
//                           Twilio. Requires SMS-channel policy +
//                           operator opt-in + provider contract.
//                           Each send is rate-limited, logged, and
//                           must respect Saudi telco compliance.
//
//   EmailInviteProvider   — sends via SendGrid / SES / Resend.
//                           Same posture as SMS: gated, audited,
//                           privacy-aware.
//
//   SocialInviteProvider  — only viable if the social platform
//                           offers an APPROVED messaging or invite
//                           API. Qift will NEVER use scraping /
//                           browser automation / unofficial
//                           reverse-engineered endpoints.
//
//   NativeShareProvider   — frontend-only; uses navigator.share()
//                           where available. No backend seam
//                           needed — the frontend invokes it
//                           against the same inviteUrl /
//                           suggestedMessage the manual provider
//                           produces.
//
// The current architecture forbids these from being added without:
//   (a) a written provider abstraction implementing this interface
//   (b) compliance + privacy review per the canonical doc
//   (c) explicit feature-flag activation (default OFF)
//   (d) operator runbook coverage similar to PHASE_7_CANARY_RUNBOOK
//
// Until then: ManualShareProvider is the ONLY provider.

export type InviteChannel = 'phone' | 'email' | 'social' | 'unknown';
export type InviteSocialPlatform =
  | 'snapchat'
  | 'tiktok'
  | 'instagram'
  | 'x'
  | 'facebook'
  | 'youtube'
  | 'threads'
  | 'telegram';

// Inputs the provider needs to render the suggested message + url.
// Intentionally narrow: no PII, no raw channel value. The provider
// has NO knowledge of phone numbers / email addresses / social
// handles — the sender will fill those in by hand when they share
// the link.
export type InviteRenderContext = {
  // Public URL the recipient will land on. Generated by the
  // service layer from token + base origin.
  inviteUrl: string;
  // Coarse channel discriminator. Drives the "Open Snapchat" /
  // "Open WhatsApp" frontend hint, but never affects the message
  // contents.
  channel: InviteChannel;
  // For social channels — which platform. Same usage note as
  // `channel`.
  platform: InviteSocialPlatform | null;
};

// Result the provider returns. Pure strings — no side-effects, no
// network calls in this MVP.
export type ManualShareResult = {
  // Public URL (echo of the input). Returned so callers don't
  // have to thread it through their own state.
  inviteUrl: string;
  // The suggested message templates — Arabic and English. Both
  // are returned; the frontend picks based on viewer locale.
  // Producers are expected to use the standard inviteUrl
  // placeholder slot {{INVITE_URL}} which the helper substitutes
  // at template time.
  suggestedMessage: {
    ar: string;
    en: string;
  };
  // For 'social' channel: a deep link that opens the platform's
  // app or web profile when known and safe. The frontend renders
  // an "Open Snapchat" / "Open TikTok" button only when this is
  // set. Null when no safe scheme is known.
  //
  // PRIVACY: we do NOT pre-fill the recipient's handle in any
  // deep link — Qift never knows the handle (the sender typed it
  // into /search and we deliberately don't store it). The deep
  // link opens the platform's HOME, the user manually navigates
  // to the recipient's profile.
  platformOpenUrl: string | null;
};

// The provider interface. Future SMS / Email / Social
// implementations will accept different inputs (the recipient's
// channel value at minimum) — those signatures will diverge from
// the manual-share shape. To keep this seam honest, we don't
// pretend a single interface fits both. The InvitationService
// dispatches to the right provider based on operator-active
// config; new providers add new method signatures.
export interface IManualShareProvider {
  render(ctx: InviteRenderContext): ManualShareResult;
}

// ── ManualShareProvider implementation ─────────────────────────

// Calm message templates. Single line, privacy-aware, no
// pressure copy, no claim of an existing gift (the MVP only
// supports general invites). Future gift-tied invites will need
// their own templates AND a separate provider call —
// project_invitation_architecture.md documents the boundary.
const TEMPLATE_AR =
  'هلا، أرسلت لك رابط دعوة لقفت. قفت يساعدك تستقبل الهدايا بدون ما تشارك عنوانك مع المرسل. سجل واربط حسابك هنا: {{INVITE_URL}}';
const TEMPLATE_EN =
  "Hi, I'm inviting you to Qift. Qift lets you receive gifts without sharing your address with the sender. Join and link your account here: {{INVITE_URL}}";

// Safe platform-open URLs. Each one is a public URL that opens
// the platform's app/home; nothing here pre-fills a target user.
// Adding a platform requires a verified, stable URL scheme.
const PLATFORM_OPEN_URL: Record<InviteSocialPlatform, string | null> = {
  snapchat: 'https://www.snapchat.com/',
  tiktok: 'https://www.tiktok.com/',
  instagram: 'https://www.instagram.com/',
  x: 'https://x.com/',
  facebook: 'https://www.facebook.com/',
  youtube: 'https://www.youtube.com/',
  threads: 'https://www.threads.net/',
  telegram: 'https://t.me/',
};

export class ManualShareProvider implements IManualShareProvider {
  render(ctx: InviteRenderContext): ManualShareResult {
    const ar = TEMPLATE_AR.replace('{{INVITE_URL}}', ctx.inviteUrl);
    const en = TEMPLATE_EN.replace('{{INVITE_URL}}', ctx.inviteUrl);
    const platformOpenUrl =
      ctx.channel === 'social' && ctx.platform
        ? (PLATFORM_OPEN_URL[ctx.platform] ?? null)
        : null;
    return {
      inviteUrl: ctx.inviteUrl,
      suggestedMessage: { ar, en },
      platformOpenUrl,
    };
  }
}
